[project]
name = "streamlit_app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "rich>=14.0.0",
    "streamlit>=1.45.1",
    "toml>=0.10.2",
    "typer>=0.16.0",
]

[dependency-groups]
dev = []
